"""Always-on knowledge block assembler (Fork 15).

The agent's system prompt always carries the universal preconditions —
6 Business Rules, 4 Data Quirks, 4 Metric Definitions (the chunks with
``section_kind ∈ ALWAYS_ON_KINDS``). That content is concatenated by
:func:`assemble_always_on_block` into a deterministically-ordered
Markdown block and written to ``backend/prompts/knowledge_always_on.md``
so the prompt assembler (``agent/prompt.py``) can pick it up alongside
the hand-authored section files.

Stable ordering matters: Anthropic's prompt cache (Fork 55) keys off
the byte sequence of the system prefix, and a non-deterministic
ordering would silently rotate the cache on every run. The sort key
``(section_kind, section_id, chunk_id)`` is canonical and immutable.

The generated file is committed to source control so:

- Reviewers see the exact content that lands in the system prompt.
- The snapshot test in ``tests/unit/agent/test_prompt_snapshot.py`` can
  fail loudly if the rendered prompt drifts without a matching
  ``PROMPT_VERSION`` bump.
- ``feat/prompts-and-tools`` doesn't need an app bootstrap path to
  regenerate the file on every run — the developer regenerates
  explicitly when the chunker registry changes.

Regenerate (from the ``backend/`` directory)::

    uv run python -m customs_agent.rag.always_on
"""

from pathlib import Path

from customs_agent.rag.chunker import Chunk, parse_chunks

ALWAYS_ON_KINDS: frozenset[str] = frozenset({"rule", "quirk", "metric"})

# Project layout: backend/src/customs_agent/rag/always_on.py
#                  → backend/prompts/knowledge_always_on.md
PROMPTS_DIR = Path(__file__).resolve().parent.parent.parent.parent / "prompts"
ALWAYS_ON_MD_PATH = PROMPTS_DIR / "knowledge_always_on.md"

_GENERATED_HEADER = """<!--
  This file is GENERATED by assemble_always_on_block() in
  backend/src/customs_agent/rag/always_on.py.

  Regenerate (from the backend/ directory):

      uv run python -m customs_agent.rag.always_on

  Do not hand-edit. Edits will be overwritten the next time the
  generator runs and the snapshot test will flag the drift.
-->
"""


def _extract_body(enriched_text: str) -> str:
    """Strip the chunker's ``DOCUMENT:`` / ``SECTION:`` enrichment prefix.

    The chunker prepends two header lines plus a blank line to each chunk's
    text so embeddings carry section placement. For the in-prompt always-on
    block we render the section title ourselves via the ``### …`` header, so
    the prefix becomes redundant noise (and burns cache tokens). Strip it.

    Defensive: if the prefix isn't found (e.g., chunker changes), return
    the text unchanged.
    """
    lines = enriched_text.split("\n", 3)
    if (
        len(lines) >= 4
        and lines[0].startswith("DOCUMENT:")
        and lines[1].startswith("SECTION:")
        and lines[2] == ""
    ):
        return lines[3]
    return enriched_text


def assemble_always_on_block(chunks: list[Chunk]) -> str:
    """Concatenate always-on chunks into a stable Markdown block.

    Parameters
    ----------
    chunks
        Output of :func:`customs_agent.rag.chunker.parse_chunks` — the
        full corpus. Only chunks whose ``section_kind`` is in
        :data:`ALWAYS_ON_KINDS` (``rule`` / ``quirk`` / ``metric``)
        contribute.

    Returns
    -------
    str
        Markdown block, sections separated by blank lines. Stable across
        runs given identical input.
    """
    selected = sorted(
        (c for c in chunks if c.section_kind in ALWAYS_ON_KINDS),
        key=lambda c: (c.section_kind, c.section_id, c.chunk_id),
    )
    parts: list[str] = []
    for c in selected:
        body = _extract_body(c.text)
        parts.append(f"### {c.doc_title} — {c.section_title}\n\n{body}\n")
    return "\n".join(parts)


def write_always_on_md(out_path: Path = ALWAYS_ON_MD_PATH) -> Path:
    """Render the always-on block and write to ``knowledge_always_on.md``.

    Emits the generated-file header banner followed by the assembled
    Markdown block. Returns the path written (so callers can echo it).
    """
    chunks = parse_chunks()
    block = assemble_always_on_block(chunks)
    out_path.write_text(_GENERATED_HEADER + "\n" + block)
    return out_path


if __name__ == "__main__":  # pragma: no cover
    path = write_always_on_md()
    print(f"Wrote {path}")
