"""Generate the canonical ground-truth fixture for the 11 case-study questions.

Run via:  ``make ground-truth``
   or:    ``cd backend && uv run python -m tests.ground_truth``

This script is the **authoritative answer source** for the project. All 11
answers are computed inline via raw SQL against the data layer's
``entries_v`` / ``entry_lines_v`` views (Fork 19). The eventual tool
implementations (``feat/prompts-and-tools`` branch) MUST match the numeric
outputs produced here — the two-axis eval grading on
``feat/remaining-tools-and-eval`` validates both the answer (correctness)
and the routing (architecture).

The generated ``ground_truth.json`` is pinned to the source CSV via
SHA-256; ``conftest.py`` (arriving on ``test/backend-units``) will fail
tests fast if the dataset drifts.

Per PROGRESS.md, the JSON output MUST be manually spreadsheet-verified
before committing — this is the highest-stakes file in the project.
"""

import json
import sys
from datetime import UTC, datetime
from decimal import Decimal
from hashlib import sha256
from pathlib import Path
from typing import Any

import duckdb

from customs_agent.data.load import CSV_PATH, load_entries
from customs_agent.data.validation import validate_loaded_data
from customs_agent.data.views import create_views

# Output path — regenerated by `make ground-truth`.
OUTPUT_PATH = Path(__file__).parent / "ground_truth.json"


# ─────────────────────────────────────────────────────────────────────────────
# Static metadata (questions, tiers, tools, citations, tolerances, phrases)
# ─────────────────────────────────────────────────────────────────────────────

QUESTIONS: dict[int, str] = {
    1: "How many customs entries were filed for Pacific Coast Apparel in January 2025?",
    2: "What is the total entered value for Summit Athletic Gear in Q1 2025?",
    3: "Which port of entry handled the most entries overall?",
    4: "What is the total Section 301 duty exposure for all customers combined in December 2024?",
    5: (
        "What is the effective duty rate for Meridian Home Furnishings for goods "
        "originating from China in Q1 2025?"
    ),
    6: (
        "How many entries are currently on hold, and what's the hold rate? "
        "Is it above or below the industry benchmark?"
    ),
    7: (
        "Compare the IEEPA duty impact across all three customers for February and "
        "March 2025. Which customer has the highest IEEPA exposure as a percentage "
        "of their total duty spend?"
    ),
    8: (
        "For Pacific Coast Apparel, what are the top 5 HTS codes by total duty "
        "contribution (all duty types combined) from China? Include the description "
        "and total amount."
    ),
    9: (
        "Generate a mini QBR summary for Summit Athletic Gear covering Q1 2025 — "
        "entry volume trend by month, total duty breakdown by program, top sourcing "
        "countries, and hold rate."
    ),
    10: (
        "If I ask 'how many entries in January?' — which date field should the agent "
        "use, and why?"
    ),
    11: (
        "What's the difference between entry count and line count for Meridian Home "
        "Furnishings in November 2024?"
    ),
}

TIERS: dict[int, int] = {
    1: 1, 2: 1, 3: 1,       # Tier 1 — direct retrieval
    4: 2, 5: 2, 6: 2,       # Tier 2 — knowledge-grounded computation
    7: 3, 8: 3, 9: 3,       # Tier 3 — multi-step reasoning
    10: 4, 11: 4,           # Tier 4 — edge cases & precision
}

EXPECTED_TOOL_NAMES: dict[int, str] = {
    1: "query_entries",
    2: "query_entries",
    3: "query_entries",
    4: "total_duty_breakdown",
    5: "effective_duty_rate",
    6: "hold_summary",
    7: "compare_customers",
    8: "top_hts_by_duty",
    9: "qbr_summary",
    10: "lookup_knowledge",
    11: "query_entries",
}

# Placeholder chunk-IDs. The RAG chunker on feat/rag-pipeline must emit these
# exact IDs for the corresponding KB sections so the eval suite can verify
# the agent retrieved them by chunk_id match.
EXPECTED_CITATIONS: dict[int, list[str]] = {
    1:  ["rule_1_date_filtering"],
    2:  ["rule_1_date_filtering"],
    3:  [],
    4:  ["quirk_1_section_301_china_only"],
    5:  ["metric_effective_duty_rate"],
    6:  ["metric_hold_rate_benchmark"],
    7:  ["quirk_2_ieepa_feb_2025", "metric_effective_duty_rate"],
    8:  ["hts_format_xxxx_xx_xxxx", "quirk_1_section_301_china_only"],
    9:  ["qbr_structure", "metric_hold_rate_benchmark", "metric_effective_duty_rate"],
    10: ["rule_1_date_filtering"],
    11: ["rule_2_entry_vs_line_count"],
}

# Q9-only LLM-as-judge rubric (Fork 8). Embedded so the eval suite can load
# it at test time without hardcoding the rubric in test code.
Q9_RUBRIC: dict[str, Any] = {
    "judge_model": "gpt-4o-mini",
    "temperature": 0,
    "seed": 42,
    "components": [
        "entry_volume_by_month",
        "duty_breakdown_by_program",
        "top_countries",
        "hold_rate",
    ],
    "pass_threshold": 3,  # >= 3/4 components present per Fork 46
}

TOLERANCES: dict[int, dict[str, Any]] = {
    1:  {"entry_count": 0},
    2:  {"total_entered_value": ["abs", 0.01]},
    3:  {"entry_count": 0},
    4:  {"section_301": ["abs", 0.01]},
    5:  {"rate_pct": ["rel", 0.001]},
    6:  {"hold_rate_pct": ["abs", 0.01], "entries_on_hold": 0, "entries_total": 0},
    7:  {"ieepa_pct": ["rel", 0.001]},
    8:  {"total_duty": ["abs", 0.01]},
    9:  {"hold_rate_pct": ["abs", 0.01]},
    10: {},
    11: {"entry_count": 0, "line_count": 0, "difference": 0},
}

EXPECTED_PHRASES: dict[int, list[str]] = {
    1: [],
    2: [],
    3: [],
    4: [],
    5: ["effective duty rate"],
    6: ["benchmark"],
    7: [],
    8: [],
    9: [],
    10: ["Release Date"],
    11: ["entry", "line"],
}

EXPECTED_TOOL_ARGS: dict[int, dict[str, Any]] = {
    1:  {"filters": {"customer_code": "PCA", "release_year_month": "2025-01"}},
    2:  {"filters": {"customer_code": "SAG", "release_year_quarter": "2025-Q1"}},
    3:  {"group_by": ["port_of_entry_code", "port_of_entry_name"]},
    4:  {"filters": {"release_year_month": "2024-12"}},
    5:  {
        "filters": {
            "customer_code": "MHF",
            "country_of_origin_code": "CN",
            "release_year_quarter": "2025-Q1",
        }
    },
    6:  {"filters": {}},
    7:  {
        "metric": "ieepa_pct",
        "filters": {
            "release_date_from": "2025-02-01",
            "release_date_to": "2025-03-31",
        },
    },
    8:  {
        "filters": {"customer_code": "PCA", "country_of_origin_code": "CN"},
        "limit": 5,
    },
    9:  {"customer_code": "SAG", "period": "2025-Q1"},
    10: {},
    11: {"filters": {"customer_code": "MHF", "release_year_month": "2024-11"}},
}


# ─────────────────────────────────────────────────────────────────────────────
# JSON encoder helper
# ─────────────────────────────────────────────────────────────────────────────

def _decimal_default(obj: Any) -> str:
    """Serialize ``decimal.Decimal`` as a string to preserve precision.

    Standard ``json.dumps`` rejects Decimal; converting to float would lose
    precision on the duty/value sums. The eval suite parses these back as
    ``Decimal(...)`` for tolerance comparisons.
    """
    if isinstance(obj, Decimal):
        return str(obj)
    raise TypeError(f"unencodable type: {type(obj).__name__}")


# ─────────────────────────────────────────────────────────────────────────────
# Per-question SQL computations
# ─────────────────────────────────────────────────────────────────────────────

def q1(con: duckdb.DuckDBPyConnection) -> dict[str, Any]:
    """Tier 1: PCA entries in Jan 2025."""
    row = con.execute(
        """
        SELECT COUNT(*) AS entry_count
        FROM entries_v
        WHERE customer_code = 'PCA'
          AND release_year_month = '2025-01'
          AND NOT is_shell
        """
    ).fetchone()
    assert row is not None
    return {"entry_count": row[0]}


def q2(con: duckdb.DuckDBPyConnection) -> dict[str, Any]:
    """Tier 1: SAG total entered value Q1 2025."""
    row = con.execute(
        """
        SELECT SUM(total_entered_value) AS total_entered_value
        FROM entries_v
        WHERE customer_code = 'SAG'
          AND release_year_quarter = '2025-Q1'
          AND NOT is_shell
        """
    ).fetchone()
    assert row is not None
    return {"total_entered_value": row[0]}


def q3(con: duckdb.DuckDBPyConnection) -> dict[str, Any]:
    """Tier 1: top port of entry by distinct entry count."""
    row = con.execute(
        """
        SELECT port_of_entry_code, port_of_entry_name, COUNT(*) AS entry_count
        FROM entries_v
        WHERE NOT is_shell
        GROUP BY port_of_entry_code, port_of_entry_name
        ORDER BY entry_count DESC
        LIMIT 1
        """
    ).fetchone()
    assert row is not None
    return {
        "port_of_entry_code": row[0],
        "port_of_entry_name": row[1],
        "entry_count": row[2],
    }


def q4(con: duckdb.DuckDBPyConnection) -> dict[str, Any]:
    """Tier 2: total Section 301 duty in Dec 2024 (all customers)."""
    row = con.execute(
        """
        SELECT COALESCE(SUM(total_section_301_duty), 0) AS section_301
        FROM entries_v
        WHERE release_year_month = '2024-12'
          AND NOT is_shell
        """
    ).fetchone()
    assert row is not None
    return {"section_301": row[0]}


def q5(con: duckdb.DuckDBPyConnection) -> dict[str, Any]:
    """Tier 2: effective duty rate for MHF, CN origin, Q1 2025.

    Formula per KB ``customer_profiles_qbr_metrics.txt`` METRIC DEFINITIONS:
        (Total Duties + Fees) / Total Entered Value * 100
    """
    row = con.execute(
        """
        SELECT
            SUM(total_duty_taxes_fees)         AS total_duty,
            SUM(entered_value)                 AS total_entered_value,
            CASE WHEN SUM(entered_value) > 0
                 THEN CAST(SUM(total_duty_taxes_fees) AS DOUBLE)
                      / SUM(entered_value) * 100.0
                 ELSE 0
            END                                 AS effective_rate_pct,
            COUNT(*)                            AS line_count
        FROM entry_lines_v
        WHERE customer_code = 'MHF'
          AND country_of_origin_code = 'CN'
          AND release_year_quarter = '2025-Q1'
          AND NOT is_shell
        """
    ).fetchone()
    assert row is not None
    return {
        "rate_pct": round(float(row[2]), 4),
        "total_duty": row[0],
        "total_entered_value": row[1],
        "line_count": row[3],
    }


def q6(con: duckdb.DuckDBPyConnection) -> dict[str, Any]:
    """Tier 2: entries on hold + hold rate vs. industry benchmark (5%; >8% warrants)."""
    row = con.execute(
        """
        SELECT
            COUNT(*)                                                  AS total_entries,
            COUNT(*) FILTER (WHERE on_hold)                           AS entries_on_hold,
            100.0 * COUNT(*) FILTER (WHERE on_hold) / COUNT(*)        AS hold_rate_pct
        FROM entries_v
        WHERE NOT is_shell
        """
    ).fetchone()
    assert row is not None
    rate = float(row[2])
    status = (
        "warrants_investigation" if rate > 8.0
        else "above"             if rate > 5.0
        else "below"
    )
    return {
        "entries_total": row[0],
        "entries_on_hold": row[1],
        "hold_rate_pct": round(rate, 4),
        "benchmark_pct": 5.0,
        "status": status,
    }


def q7(con: duckdb.DuckDBPyConnection) -> dict[str, Any]:
    """Tier 3: IEEPA % of total duty per customer, Feb-Mar 2025; rank desc.

    Uses ``entries_v`` columns (which already encode the per-entry MPF cap)
    so the IEEPA percentage denominator is correctly capped at the entry
    grain - re-deriving from line grain would over-count MPF.
    """
    rows = con.execute(
        """
        WITH per_customer AS (
            SELECT
                customer_code,
                COALESCE(SUM(total_ieepa_duty), 0)        AS ieepa,
                (
                    SUM(total_primary_duty)
                    + COALESCE(SUM(total_section_301_duty), 0)
                    + COALESCE(SUM(total_ieepa_duty), 0)
                    + SUM(total_mpf_capped)
                    + SUM(total_hmf)
                )                                          AS total_duty
            FROM entries_v
            WHERE release_date BETWEEN DATE '2025-02-01' AND DATE '2025-03-31'
              AND NOT is_shell
            GROUP BY customer_code
        )
        SELECT
            customer_code,
            ieepa,
            total_duty,
            CASE WHEN total_duty > 0
                 THEN 100.0 * ieepa / total_duty
                 ELSE 0
            END AS ieepa_pct
        FROM per_customer
        ORDER BY ieepa_pct DESC
        """
    ).fetchall()
    ranked = [
        {
            "customer_code": r[0],
            "ieepa": r[1],
            "total_duty": r[2],
            "ieepa_pct": round(float(r[3]), 4),
            "rank": i + 1,
        }
        for i, r in enumerate(rows)
    ]
    return {
        "ranked": ranked,
        "highest_customer_code": ranked[0]["customer_code"] if ranked else None,
    }


def q8(con: duckdb.DuckDBPyConnection) -> dict[str, Any]:
    """Tier 3: top 5 HTS codes by total duty for PCA + CN origin."""
    rows = con.execute(
        """
        SELECT
            hts_code,
            ANY_VALUE(hts_description)                AS hts_description,
            SUM(primary_duty)
                + COALESCE(SUM(section_301_duty), 0)
                + COALESCE(SUM(ieepa_duty), 0)
                + SUM(mpf)
                + SUM(hmf)                            AS total_duty,
            SUM(primary_duty)                         AS primary_duty,
            COALESCE(SUM(section_301_duty), 0)        AS section_301,
            COALESCE(SUM(ieepa_duty), 0)              AS ieepa,
            COUNT(*)                                  AS line_count,
            SUM(entered_value)                        AS entered_value
        FROM entry_lines_v
        WHERE customer_code = 'PCA'
          AND country_of_origin_code = 'CN'
          AND NOT is_shell
        GROUP BY hts_code
        ORDER BY total_duty DESC
        LIMIT 5
        """
    ).fetchall()
    return {
        "top_5": [
            {
                "hts_code": r[0],
                "hts_description": r[1],
                "total_duty": r[2],
                "primary_duty": r[3],
                "section_301": r[4],
                "ieepa": r[5],
                "line_count": r[6],
                "entered_value": r[7],
            }
            for r in rows
        ]
    }


def q9(con: duckdb.DuckDBPyConnection) -> dict[str, Any]:
    """Tier 3: QBR summary for SAG Q1 2025.

    Composes four sub-views: entry volume by month, duty breakdown,
    top sourcing countries, and hold rate.
    """
    volume_rows = con.execute(
        """
        SELECT release_year_month, COUNT(*) AS entry_count
        FROM entries_v
        WHERE customer_code = 'SAG'
          AND release_year_quarter = '2025-Q1'
          AND NOT is_shell
        GROUP BY release_year_month
        ORDER BY release_year_month
        """
    ).fetchall()

    duty_row = con.execute(
        """
        SELECT
            SUM(total_primary_duty)                   AS primary_duty,
            COALESCE(SUM(total_section_301_duty), 0)  AS section_301,
            COALESCE(SUM(total_ieepa_duty), 0)        AS ieepa,
            SUM(total_mpf_capped)                     AS mpf_capped,
            SUM(total_hmf)                            AS hmf
        FROM entries_v
        WHERE customer_code = 'SAG'
          AND release_year_quarter = '2025-Q1'
          AND NOT is_shell
        """
    ).fetchone()
    assert duty_row is not None

    country_rows = con.execute(
        """
        SELECT country_of_origin_code, COUNT(*) AS line_count
        FROM entry_lines_v
        WHERE customer_code = 'SAG'
          AND release_year_quarter = '2025-Q1'
          AND NOT is_shell
        GROUP BY country_of_origin_code
        ORDER BY line_count DESC
        LIMIT 5
        """
    ).fetchall()

    hold_row = con.execute(
        """
        SELECT
            COUNT(*)                                                  AS total,
            COUNT(*) FILTER (WHERE on_hold)                           AS on_hold,
            100.0 * COUNT(*) FILTER (WHERE on_hold) / COUNT(*)        AS rate
        FROM entries_v
        WHERE customer_code = 'SAG'
          AND release_year_quarter = '2025-Q1'
          AND NOT is_shell
        """
    ).fetchone()
    assert hold_row is not None

    return {
        "entry_volume_by_month": [
            {"month": r[0], "count": r[1]} for r in volume_rows
        ],
        "duty_breakdown": {
            "primary": duty_row[0],
            "section_301": duty_row[1],
            "ieepa": duty_row[2],
            "mpf_capped": duty_row[3],
            "hmf": duty_row[4],
            "total": (
                duty_row[0] + duty_row[1] + duty_row[2] + duty_row[3] + duty_row[4]
            ),
        },
        "top_countries": [
            {"country_of_origin_code": r[0], "line_count": r[1]} for r in country_rows
        ],
        "hold_summary": {
            "entries_total": hold_row[0],
            "entries_on_hold": hold_row[1],
            "hold_rate_pct": round(float(hold_row[2]), 4),
        },
    }


def q10(con: duckdb.DuckDBPyConnection) -> dict[str, Any]:
    """Tier 4: knowledge question — which date field for monthly queries?

    The agent's prose answer should reference "Release Date" and cite KB
    Business Rule 1. The structured shape here just states the expected
    field name; prose-level checks happen via ``expected_phrases``.
    """
    return {"date_field": "release_date"}


def q11(con: duckdb.DuckDBPyConnection) -> dict[str, Any]:
    """Tier 4: entry count vs. line count for MHF in Nov 2024."""
    row = con.execute(
        """
        SELECT
            COUNT(DISTINCT entry_number) AS entry_count,
            COUNT(*)                     AS line_count
        FROM entry_lines_v
        WHERE customer_code = 'MHF'
          AND release_year_month = '2024-11'
          AND NOT is_shell
        """
    ).fetchone()
    assert row is not None
    return {
        "entry_count": row[0],
        "line_count": row[1],
        "difference": row[1] - row[0],
    }


# ─────────────────────────────────────────────────────────────────────────────
# Fixture assembly + main
# ─────────────────────────────────────────────────────────────────────────────

def build_fixture(con: duckdb.DuckDBPyConnection) -> dict[str, Any]:
    """Compute every answer and assemble the fixture dict."""
    computers = {
        1: q1, 2: q2, 3: q3, 4: q4, 5: q5, 6: q6,
        7: q7, 8: q8, 9: q9, 10: q10, 11: q11,
    }
    questions: list[dict[str, Any]] = []
    for q_id in range(1, 12):
        entry: dict[str, Any] = {
            "id": q_id,
            "tier": TIERS[q_id],
            "query": QUESTIONS[q_id],
            "answer": computers[q_id](con),
            "tolerance": TOLERANCES[q_id],
            "expected_phrases": EXPECTED_PHRASES[q_id],
            "expected_citations": EXPECTED_CITATIONS[q_id],
            "expected_tool_name": EXPECTED_TOOL_NAMES[q_id],
            "expected_tool_args_partial": EXPECTED_TOOL_ARGS[q_id],
        }
        if q_id == 9:
            entry["rubric"] = Q9_RUBRIC
        questions.append(entry)
    return {
        "version": "1.0.0",
        "generated_at": datetime.now(UTC).isoformat(),
        "dataset_sha256": sha256(CSV_PATH.read_bytes()).hexdigest(),
        "questions": questions,
    }


def main() -> None:
    """Bring up the data layer, compute the 11 answers, write the JSON."""
    con = duckdb.connect(":memory:")
    load_entries(con)
    create_views(con)
    validate_loaded_data(con)
    fixture = build_fixture(con)
    OUTPUT_PATH.write_text(
        json.dumps(fixture, indent=2, default=_decimal_default) + "\n"
    )
    print(
        f"Wrote {OUTPUT_PATH} ({len(fixture['questions'])} questions)",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
