"""Pydantic-settings ``Settings`` class — the source of truth for all
env-bound configuration.

Configuration is loaded from environment variables (case-insensitive)
with a fallback to a ``.env`` file at the ``backend/`` root. The
``.env`` file itself is gitignored; the committed
``backend/.env.example`` contract documents every variable in this
class.

The four logical config groupings referenced in PROGRESS.md
(``AgentConfig`` / ``LLMConfig`` / ``RateLimitConfig`` /
``SafetyConfig``) are represented as sections inside this single
class, not as separate models — this matches the locked spec in
``context/05-api-and-backend.md`` and keeps env-var binding flat and
predictable.

The module-level ``settings = Settings()`` singleton lives in this
package's :mod:`__init__.py` so importers can write
``from customs_agent.config import settings`` without binding to the
private module name. The first import raises ``pydantic.ValidationError``
if the three required env vars (``ANTHROPIC_API_KEY``,
``BACKEND_API_KEY``, ``ALLOWED_ORIGINS``) are absent.
"""

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Application settings loaded from environment variables and ``.env``."""

    # === LLM (Forks 5, 13, 26 + G1) ============================================
    anthropic_api_key: str
    """Anthropic API key for the main agent model. Required."""

    openai_api_key: str = ""
    """OpenAI key for RAG embeddings (build-time, Fork 13) and the eval judge
    (Fork 8). Not read at runtime once the index is built."""

    llm_model: str = "claude-sonnet-4-6"
    """Main agent model alias (not a dated pin); resolved by Anthropic's API."""

    llm_judge_model: str = "gpt-4o-mini"
    """OpenAI model used by the Q9 LLM-as-judge eval rubric (Fork 8). Eval-only."""

    llm_embedding_model: str = "text-embedding-3-small"
    """OpenAI embedding model used at build-time RAG indexing (Fork 13). Build-only."""

    llm_temperature: float = 0.0
    """Sampling temperature for the agent. Always 0 per Fork 26 (determinism)."""

    llm_seed: int = 42
    """Random seed for the OpenAI judge (Anthropic doesn't expose seed). Fork 26."""

    # === Auth (Fork 48) ========================================================
    backend_api_key: str
    """Static API key validated via the ``X-API-Key`` header. Required.
    Generated by ``scripts/setup.sh`` via ``openssl rand -base64 32``."""

    # === CORS (Fork 38) ========================================================
    allowed_origins: str
    """Comma-separated CORS allowlist. Entries wrapped in ``^...$`` are treated
    as regex patterns (e.g., ``^https://.*\\.vercel\\.app$``); other entries
    match by exact string. Required."""

    # === Observability (Fork 10, 54) ===========================================
    langfuse_public_key: str = ""
    """Langfuse Cloud public key. Optional — empty disables Langfuse traces."""

    langfuse_secret_key: str = ""
    """Langfuse Cloud secret key. Optional — empty disables Langfuse traces."""

    langfuse_host: str = "https://cloud.langfuse.com"
    """Langfuse Cloud endpoint."""

    environment: str = "development"
    """Either ``"development"`` or ``"production"``. ``"production"`` switches
    structlog from ConsoleRenderer to JSONRenderer per Fork 54 — set in
    ``fly.toml`` only."""

    # === Agent tuning (Fork 23) ================================================
    agent_max_iterations: int = 5
    """Max iterations the agent loop will run before forcing a degraded response."""

    agent_max_input_tokens_per_turn: int = 50_000
    """Per-turn input token budget (history + retrieved chunks + user message)."""

    agent_max_output_tokens_per_turn: int = 8_000
    """Per-turn max output token allocation for the LLM."""

    # === Rate limit (Fork 47) ==================================================
    ratelimit_enabled: bool = True
    """Master switch for slowapi rate limiting. Disable for local load tests."""

    ratelimit_chat_per_minute: int = 20
    """Per-(key, IP) limit for ``/chat`` and ``/chat/stream``."""

    ratelimit_starter_prompts_per_minute: int = 60
    """Per-(key, IP) limit for ``/api/starter-prompts``."""

    # === Safety (Fork 49) ======================================================
    safety_max_user_message_chars: int = 2000
    """Hard char cap on the user message field (Fork 49 layer 1, request-size
    guard against length-bomb attacks)."""

    safety_output_sanity_check_enabled: bool = True
    """Run the regex-based output secret-pattern scrubber on the final agent
    response (Fork 49 layer 5)."""

    # === Pydantic-settings config ==============================================
    model_config = SettingsConfigDict(env_file=".env", case_sensitive=False)

    # === Derived CORS helpers ==================================================

    @property
    def cors_exact_origins(self) -> list[str]:
        """Allowed origins that match by exact string (no leading ``^``)."""
        entries = [o.strip() for o in self.allowed_origins.split(",") if o.strip()]
        return [o for o in entries if not (o.startswith("^") and o.endswith("$"))]

    @property
    def cors_combined_regex(self) -> str | None:
        """Combined OR'd regex of all ``^...$`` allowlist entries.

        Returns ``None`` when no regex entries are configured — callers should
        skip ``allow_origin_regex=`` in the CORS middleware setup in that case.
        """
        entries = [o.strip() for o in self.allowed_origins.split(",") if o.strip()]
        patterns = [o for o in entries if o.startswith("^") and o.endswith("$")]
        return "|".join(f"({p})" for p in patterns) if patterns else None
